export const sampleData = {
  chartData: {
    labels: ["March", "April", "May", "June", "July", "August"],
    datasets: [
      {
        label: "RFP's Intake",
        data: [85, 90, 150, 60, 180, 90],
        borderRadius: 8,
      },
      {
        label: "RFP's Submitted",
        data: [75, 70, 80, 50, 90, 80],
        borderRadius: 8,
      },
      {
        label: "RFP's Won",
        data: [35, 30, 75, 45, 85, 35],
        borderRadius: 8,
      },
    ],
  },

  pieData: {
    labels: ["Won RFPs", "Submitted RFPs"],
    datasets: [
      {
        data: [25, 75],
        borderWidth: 3,
      },
    ],
  },

  f1GridRFPs: [
    {
      id: 1,
      title: "Cloud Migration for Acme Corp",
      company: "Acme Corporation",
      createdOn: "2024-03-15",
      due: "2024-04-15",
      status: "open",
      priority: "HIGH",
      budget: "$250K",
      teamMembers: 3,
      completion: 75,
      isNew: true,
    },
    {
      id: 2,
      title: "Security Audit Services - Zeta Inc",
      company: "Zeta Inc",
      createdOn: "2024-03-14",
      due: "2024-04-20",
      status: "in-review",
      priority: "MEDIUM",
      budget: "$180K",
      teamMembers: 2,
      completion: 60,
      isNew: true,
    },
    {
      id: 3,
      title: "HR Software Implementation",
      company: "HRNet Solutions",
      createdOn: "2024-03-12",
      due: "2024-05-01",
      status: "open",
      priority: "LOW",
      budget: "$420K",
      teamMembers: 4,
      completion: 30,
      isNew: false,
    },
    {
      id: 4,
      title: "E-commerce Platform Upgrade",
      company: "ShopFast Ltd",
      createdOn: "2024-03-10",
      due: "2024-04-25",
      status: "pending",
      priority: "HIGH",
      budget: "$320K",
      teamMembers: 5,
      completion: 45,
      isNew: false,
    },
    {
      id: 5,
      title: "Mobile App Development",
      company: "TechStart Inc",
      createdOn: "2024-03-08",
      due: "2024-05-15",
      status: "approved",
      priority: "MEDIUM",
      budget: "$150K",
      teamMembers: 3,
      completion: 85,
      isNew: false,
    },
    {
      id: 6,
      title: "Data Analytics Dashboard",
      company: "DataViz Corp",
      createdOn: "2024-03-05",
      due: "2024-04-30",
      status: "closed",
      priority: "LOW",
      budget: "$95K",
      teamMembers: 2,
      completion: 100,
      isNew: false,
    },
  ],

  allRFPs: [
    {
      id: 1,
      title: "Enterprise CRM Implementation",
      company: "Acme Corporation",
      createdOn: "02 Mar 2025",
      due: "02 Apr 2025",
      status: "in-review",
      priority: "HIGH",
      budget: "$250,000",
      teamMembers: 2,
      completion: 1,
      tags: ["enterprise", "crm", "high-priority"],
    },
    {
      id: 2,
      title: "Healthcare Management System",
      company: "MedTech Solutions",
      createdOn: "05 Mar 2025",
      due: "20 Apr 2025",
      status: "approved",
      priority: "MEDIUM",
      budget: "$180,000",
      teamMembers: 3,
      completion: 5,
      tags: ["healthcare", "compliance"],
    },
    {
      id: 3,
      title: "Financial Services Platform",
      company: "FinanceFlex Bank",
      createdOn: "10 Mar 2025",
      due: "30 May 2025",
      status: "pending",
      priority: "LOW",
      budget: "$420,000",
      teamMembers: 1,
      completion: 0,
      tags: ["finance", "banking"],
    },
    {
      id: 4,
      title: "E-commerce Platform Redesign",
      company: "ShopSmart Inc",
      createdOn: "15 Mar 2025",
      due: "25 Apr 2025",
      status: "open",
      priority: "HIGH",
      budget: "$320,000",
      teamMembers: 4,
      completion: 3,
      tags: ["ecommerce", "ui/ux", "mobile"],
    },
    {
      id: 5,
      title: "Cloud Infrastructure Migration",
      company: "TechFlow Corp",
      createdOn: "18 Mar 2025",
      due: "15 May 2025",
      status: "draft",
      priority: "MEDIUM",
      budget: "$150,000",
      teamMembers: 2,
      completion: 2,
      tags: ["cloud", "infrastructure", "aws"],
    },
    {
      id: 6,
      title: "AI-Powered Analytics Dashboard",
      company: "DataViz Solutions",
      createdOn: "22 Mar 2025",
      due: "10 Jun 2025",
      status: "open",
      priority: "HIGH",
      budget: "$280,000",
      teamMembers: 3,
      completion: 4,
      tags: ["ai", "analytics", "dashboard"],
    },
  ],
}
