import { Users, UserCheck, Clock, TrendingUp } from "lucide-react"

export const teamData = {
  stats: [
    {
      icon: Users,
      value: "12",
      label: "Total Members",
    },
    {
      icon: UserCheck,
      value: "8",
      label: "Active Members",
    },
    {
      icon: Clock,
      value: "24h",
      label: "Avg Response Time",
    },
    {
      icon: TrendingUp,
      value: "85%",
      label: "Team Efficiency",
    },
  ],
  members: [
    {
      id: 1,
      name: "John Smith",
      email: "john.smith@company.com",
      phone: "+1 (555) 123-4567",
      position: "Senior Sales Manager",
      role: "Admin",
      activeRFPs: 5,
      winRate: "78%",
      performance: 92,
    },
    {
      id: 2,
      name: "Sarah Johnson",
      email: "sarah.johnson@company.com",
      phone: "+1 (555) 234-5678",
      position: "RFP Specialist",
      role: "Manager",
      activeRFPs: 8,
      winRate: "85%",
      performance: 88,
    },
    {
      id: 3,
      name: "Michael Brown",
      email: "michael.brown@company.com",
      phone: "+1 (555) 345-6789",
      position: "Technical Writer",
      role: "Member",
      activeRFPs: 3,
      winRate: "72%",
      performance: 85,
    },
    {
      id: 4,
      name: "Emily Davis",
      email: "emily.davis@company.com",
      phone: "+1 (555) 456-7890",
      position: "Business Analyst",
      role: "Member",
      activeRFPs: 6,
      winRate: "80%",
      performance: 90,
    },
    {
      id: 5,
      name: "David Wilson",
      email: "david.wilson@company.com",
      phone: "+1 (555) 567-8901",
      position: "Project Manager",
      role: "Manager",
      activeRFPs: 4,
      winRate: "88%",
      performance: 94,
    },
    {
      id: 6,
      name: "Lisa Anderson",
      email: "lisa.anderson@company.com",
      phone: "+1 (555) 678-9012",
      position: "Content Strategist",
      role: "Member",
      activeRFPs: 7,
      winRate: "76%",
      performance: 87,
    },
  ],
}
